config:
  plugin:
    metrics-by-endopoint: {}
  target: "http://localhost:9090"
  phases: # Se generan 10 usuario virtuales cada segundo por un lapso de 20s
    - duration: 20
      arrivalRate: 10 # usuarios
scenarios:
  - name: "Sessions flow (register + login)"
    flow:
      - log: "Creacion de user con FakerJS"
      - get:
          url: "/api/user/test"
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.age"
              as: "age"
            - json: "$.password"
              as: "password"
      - log: "Registro de user de FakerJS"
      - post:
          url: "/api/session/register"
          json:
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            age: "{{age}}"
            password: "{{password}}"
      - think: 2 # simula un 2s de espera
      - log: "Login de user de FakerJS previamente dado alta"
      - post:
          url: "/api/session/login"
          json:
            email: "{{email}}"
            password: "{{password}}"
